ProgramingCalssProject/Controllers/CustomerOrderController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PgrogrammingClass.Core.Domain;
using PgrogrammingClass.Data.DataContext;
using ProgramingCalssProject.Models.Utillity;

namespace ProgramingCalssProject.Controllers
{

    [Authorize]
    public class CustomerOrderController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IpersianDateTime _dt;
        private readonly UserManager<ApplicationUser> _userManager;

        public CustomerOrderController(
            ApplicationDbContext context,
            IpersianDateTime dt,
            UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _dt = dt;
            _userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentuser = await _userManager.GetUserAsync(User);

            var model = _context.TblShoppingcart.Where(a => a.UserId == currentuser.Id && a.IsPaied).ToList();


            return View(model);
        }


        public async Task<IActionResult> Details(string Id)
        {
            var currentuser = await _userManager.GetUserAsync(User);
            var model = _context.TblShoppingcart
                            .Where(a => a.Id == Id && a.UserId==currentuser.Id && a.IsPaied)
                            .Include(a => a.TblShoppingCartDetails)
                            .Include(a => a.TblUserAddress)
                            .ThenInclude(a => a.TblCity)
                            .ThenInclude(a => a.TblProvince).SingleOrDefault();

            return View(model);
        }


    }
}

ProgramingCalssProject/Views/CustomerOrder/Details.cshtml
@model PgrogrammingClass.Core.Domain.TblShoppingcart
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@inject IGetData getData
@inject IpersianDateTime dt
<div class="w3-card-2 p-3 w3-round-medium">
    <div class="p-2 w3-round-medium bg-light my-2">
        شماره فاکتور: @Model.CustomOrderNumber
    </div>
    <dl class="row">
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.IsSentToUser)
        </dt>
        <dd class="col-md-9">
            @if (Model.IsSentToUser)
            {
                <span class="text-success"><i class="fa fa-check"></i></span>
            }
            else
            {
                <span class="text-danger"><i class="fa fa-close"></i></span>
            }
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.PayDate)
        </dt>
        <dd class="col-md-9">
            @dt.GetPersinaDate(Model.PayDate)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.PriceWithoutOff)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.PriceWithoutOff)
        </dd>

        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.IsCoponSet)
        </dt>
        <dd class="col-md-9">
            @if (Model.IsCoponSet)
            {
                <span class="text-success"><i class="fa fa-check"></i></span>
            }
            else
            {
                <span class="text-danger"><i class="fa fa-close"></i></span>
            }
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.OffCopon)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.OffCopon)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.OffPercent)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.OffPercent)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.TransactionNumber)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.TransactionNumber)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.CustomOrderNumber)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.CustomOrderNumber)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.CreateDate)
        </dt>
        <dd class="col-md-9">
            @dt.GetPersinaDate(Model.CreateDate)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.ShippingWayName)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.ShippingWayName)
        </dd>
        <dt class="col-md-3">
            @Html.DisplayNameFor(model => model.ShippingPrice)
        </dt>
        <dd class="col-md-9">
            @Html.DisplayFor(model => model.ShippingPrice)
        </dd>
    </dl>
    <hr />
    <div class="bg-white w3-round-medium text-center p-2">
        محصولات
    </div>

    @foreach (var item in Model.TblShoppingCartDetails)
    {
        int totalprice = item.Price * item.Count;
        <div class="col-md-12">
            <div class="m-2 bg-white">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="@getData.GetImageByProductId(item.ProductId)" class="img-thumbnail img-fluid m-1" alt="@item.ProductName" title="@item.ProductName" width="150" />
                        </div>
                        <div class="col-md-8">
                            <div class="m-2">
                                <span class="w3-text-gray">
                                    نام محصول : @item.ProductName
                                </span>
                            </div>
                            <div class="m-2">
                                <div class="w3-text-gray d-inline-block">
                                    تعداد :@item.Count
                                </div>
                            </div>
                            <div class="m-2">
                                <span class="w3-text-gray">
                                    قیمت :@item.Price
                                </span>
                            </div>
                            <div class="m-2">
                                <span class="w3-text-gray">
                                    قیمت کل :@totalprice
                                </span>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    }
</div>



<hr />
<a asp-action="Index" asp-controller="CustomerOrder" class="btn btn-primary m-3"> بازگشت <i class=" fa fa-return"></i></a>

ProgramingCalssProject/Views/CustomerOrder/Index.cshtml
@model IEnumerable<PgrogrammingClass.Core.Domain.TblShoppingcart>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="row">
        <partial name="_AccountPartial" />
    <div class="col-md-9">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.IsSentToUser)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.TotalPrice)
                    </th>

                    <th>
                        @Html.DisplayNameFor(model => model.TransactionNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CustomOrderNumber)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.IsSentToUser)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.TotalPrice)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.TransactionNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CustomOrderNumber)
                        </td>
                        <td>
                            <a asp-action="Details" asp-route-id="@item.Id">Details</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>