ProgramingCalssProject/Areas/Admin/Controllers/BannerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PgrogrammingClass.Core.Domain;
using PgrogrammingClass.Sevices.EntitesServices;
using ProgramingCalssProject.Models;
using ProgramingCalssProject.Models.Utillity;
using System.Drawing;
using static ProgramingCalssProject.Models.Utillity.ImageProccess;

namespace ProgramingCalssProject.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;
        private Microsoft.AspNetCore.Hosting.IHostingEnvironment _hostingEnvironment;


        public BannerController(
            IBannerService bannerService,
            Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnvironment)
        {
            _bannerService = bannerService;
            _hostingEnvironment = hostingEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _bannerService.GetAll());
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblBanner model, IFormFile Pic)
        {
            ///در اولین مرحله ما چک میکنیم که اطلاعات تایید شده باشند 
            ///چک کردن تصویر، کم کردن حجم تصویر ، چک کردن تایپ تصویر 
            ///ذخیره سازی تصویر 
            ///ذخیره سازی اطلاعات در دیتابیس
            ModelState.Remove(nameof(model.Picture));

            if (!ModelState.IsValid)
            {
                TempData["W"] = ErrMsg.IncorrectInformation;
                return RedirectToAction(nameof(Index));
            }

            if (Pic == null)
            {
                TempData["W"] = "تصویری انتخاب نشده است";
                return RedirectToAction(nameof(Index));
            }

            string picName = Path.GetFileName(Pic.FileName);
            string picExtention = Path.GetExtension(picName).ToLower();

            ImageProccess imageProccess = new ImageProccess();

            var checkPic = imageProccess.CheckPic(Pic, "تصویر بنر");
            if (checkPic.Error)
            {
                TempData["W"] = checkPic.Text;
                return RedirectToAction(nameof(Index));
            }
            if (!Directory.Exists(Path.Combine(_hostingEnvironment.WebRootPath + "/Pic/Banner/")))
            {
                Directory.CreateDirectory(Path.Combine(_hostingEnvironment.WebRootPath + "/Pic/Banner/"));
            }

            string picNameDb = "/Pic/Banner/" + Guid.NewGuid().ToString() + picExtention;

            Bitmap bmp = new Bitmap(Pic.OpenReadStream());
            Image img = imageProccess.ResizeImage(bmp);

            img.Save(Path.Combine(_hostingEnvironment.WebRootPath + picNameDb));
            model.Picture = picNameDb;
            model.CreateDate=DateTime.Now;
            model.ModifyDate = DateTime.Now;
            await _bannerService.Add(model);



            TempData["S"] = ErrMsg.Success;
            return RedirectToAction(nameof(Index));
        }
    }
}

ProgramingCalssProject/Areas/Admin/Views/Banner/Index.cshtml
@model IEnumerable<PgrogrammingClass.Core.Domain.TblBanner>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>مدیریت بنر سایت</h1>

<div class="container bg-light m-2 w3-round-medium">
    <div class="row">
        <div class="col-md-12">
            <div class="bg-info w3-round-medium p-2 m-2 text-center">
                بارگزاری تصویر
            </div>
        </div>
        <form asp-controller="Banner" asp-Action="Create" method="post" asp-area="Admin" enctype="multipart/form-data">
            <div class="col-md-2">
                <label class="m-2">تصویر</label>
            </div>
            <div class="col-md-10">
                <input type="file" name="Pic" class="form-control m-2" required />
            </div>
            <div class="col-md-2">
                <label class="m-2">عنوان تصویر</label>
            </div>
            <div class="col-md-10">
                <input type="text" name="Title" class="form-control m-2" required />
            </div>
            <div class="col-md-2">
                <label class="m-2">متن جایگذین</label>
            </div>
            <div class="col-md-10">
                <input type="text" name="Alt" class="form-control m-2" required />
            </div>
            <div class="col-md-12">
                <input type="submit" value="ثبت اطلاعات" class="btn btn-primary m-2" />
            </div>
        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Picture)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Alt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreateDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifyDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>

                    <img class="img-thumbnail img-fluid" src="@item.Picture" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Alt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreateDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ModifyDate)
                </td>
                <td>
                    <a asp-action="Delete" class="btn btn-danger btn-sm" onclick="return confirm('ایا اطمینان دارید!!!')" asp-route-id="@item.Id">
                        <i class=" fa fa-trash w3-large"></i>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>